import { Download, RefreshCw, TrendingUp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { CircularProgress } from '@/components/CircularProgress';
import { MaturityHeatmap } from './MaturityHeatmap';
import { GapAnalysis } from './GapAnalysis';
import { AssessmentHistory } from './AssessmentHistory';
import jsPDF from 'jspdf';
import { OUTCOME_LABELS } from '@/data/maturityAssessmentData';

interface AssessmentResultsProps {
  result: {
    id: string;
    completed_at: string;
    overall_score: number;
    products_services_score: number;
    price_value_score: number;
    consumer_understanding_score: number;
    consumer_support_score: number;
  };
  allAssessments: Array<{
    id: string;
    completed_at: string;
    overall_score: number;
    products_services_score: number;
    price_value_score: number;
    consumer_understanding_score: number;
    consumer_support_score: number;
  }>;
  canRetake: boolean;
  daysUntilRetake: number;
  onRetake: () => void;
}

export const AssessmentResults = ({
  result,
  allAssessments,
  canRetake,
  daysUntilRetake,
  onRetake,
}: AssessmentResultsProps) => {
  const scores = {
    products_services: result.products_services_score,
    price_value: result.price_value_score,
    consumer_understanding: result.consumer_understanding_score,
    consumer_support: result.consumer_support_score,
  };

  const getMaturityLevel = (score: number): string => {
    if (score >= 80) return 'Optimised';
    if (score >= 60) return 'Managed';
    if (score >= 40) return 'Defined';
    if (score >= 20) return 'Developing';
    return 'Initial';
  };

  const exportToPDF = () => {
    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.getWidth();
    
    // Title
    pdf.setFontSize(20);
    pdf.setTextColor(0, 51, 102);
    pdf.text('Consumer Duty Maturity Assessment', pageWidth / 2, 25, { align: 'center' });
    
    // Date
    pdf.setFontSize(10);
    pdf.setTextColor(100);
    pdf.text(`Assessment Date: ${new Date(result.completed_at).toLocaleDateString('en-GB', {
      day: 'numeric',
      month: 'long',
      year: 'numeric'
    })}`, pageWidth / 2, 35, { align: 'center' });

    // Overall Score
    pdf.setFontSize(14);
    pdf.setTextColor(0);
    pdf.text('Overall Maturity Score', 20, 55);
    
    pdf.setFontSize(32);
    pdf.setTextColor(0, 102, 204);
    pdf.text(`${Math.round(result.overall_score)}%`, 20, 70);
    
    pdf.setFontSize(12);
    pdf.setTextColor(100);
    pdf.text(`Maturity Level: ${getMaturityLevel(result.overall_score)}`, 20, 80);

    // Outcome Scores
    pdf.setFontSize(14);
    pdf.setTextColor(0);
    pdf.text('Outcome Scores', 20, 100);
    
    let yPos = 115;
    const outcomeScores = [
      { label: OUTCOME_LABELS.products_services, score: scores.products_services },
      { label: OUTCOME_LABELS.price_value, score: scores.price_value },
      { label: OUTCOME_LABELS.consumer_understanding, score: scores.consumer_understanding },
      { label: OUTCOME_LABELS.consumer_support, score: scores.consumer_support },
    ];

    outcomeScores.forEach(({ label, score }) => {
      pdf.setFontSize(11);
      pdf.setTextColor(0);
      pdf.text(label, 20, yPos);
      
      // Score bar background
      pdf.setFillColor(230, 230, 230);
      pdf.rect(20, yPos + 3, 100, 6, 'F');
      
      // Score bar fill
      const color = score >= 60 ? [34, 197, 94] : score >= 40 ? [234, 179, 8] : [239, 68, 68];
      pdf.setFillColor(color[0], color[1], color[2]);
      pdf.rect(20, yPos + 3, score, 6, 'F');
      
      pdf.setFontSize(10);
      pdf.text(`${Math.round(score)}%`, 130, yPos + 7);
      
      yPos += 20;
    });

    // Gap Analysis
    yPos += 10;
    pdf.setFontSize(14);
    pdf.setTextColor(0);
    pdf.text('Gap Analysis', 20, yPos);
    
    yPos += 15;
    pdf.setFontSize(10);
    pdf.setTextColor(100);
    
    const sortedOutcomes = outcomeScores.sort((a, b) => a.score - b.score);
    const weakAreas = sortedOutcomes.filter(o => o.score < 60);
    
    if (weakAreas.length > 0) {
      pdf.text('Areas Requiring Attention:', 20, yPos);
      yPos += 8;
      weakAreas.forEach(({ label, score }) => {
        pdf.text(`• ${label} (${Math.round(score)}%)`, 25, yPos);
        yPos += 7;
      });
    } else {
      pdf.text('All areas meet minimum thresholds. Continue maintaining excellence.', 20, yPos);
    }

    // Footer
    pdf.setFontSize(8);
    pdf.setTextColor(150);
    pdf.text('Generated by Consumer Duty Playbook', pageWidth / 2, 280, { align: 'center' });
    pdf.text('This assessment is for internal use only', pageWidth / 2, 285, { align: 'center' });

    pdf.save(`maturity-assessment-${new Date().toISOString().split('T')[0]}.pdf`);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-foreground">Assessment Results</h2>
          <p className="text-muted-foreground">
            Completed on {new Date(result.completed_at).toLocaleDateString('en-GB', {
              day: 'numeric',
              month: 'long',
              year: 'numeric'
            })}
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={exportToPDF}>
            <Download className="h-4 w-4 mr-2" />
            Export PDF
          </Button>
          {canRetake ? (
            <Button onClick={onRetake}>
              <RefreshCw className="h-4 w-4 mr-2" />
              Retake Assessment
            </Button>
          ) : (
            <Button disabled variant="secondary">
              <RefreshCw className="h-4 w-4 mr-2" />
              Retake in {daysUntilRetake} days
            </Button>
          )}
        </div>
      </div>

      <div className="grid lg:grid-cols-2 gap-6">
        {/* Overall Score */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <TrendingUp className="h-5 w-5 text-primary" />
              Overall Maturity Score
            </CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col items-center py-6">
            <CircularProgress 
              value={result.overall_score} 
              size={180}
              strokeWidth={12}
            />
            <div className="mt-4 text-center">
              <div className="text-lg font-semibold text-foreground">
                {getMaturityLevel(result.overall_score)}
              </div>
              <p className="text-sm text-muted-foreground mt-1">
                {result.overall_score >= 60 
                  ? 'Good progress towards Consumer Duty compliance'
                  : 'Further work needed to meet Consumer Duty requirements'}
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Heatmap */}
        <Card>
          <CardHeader>
            <CardTitle>Outcome Heatmap</CardTitle>
          </CardHeader>
          <CardContent>
            <MaturityHeatmap scores={scores} />
            <div className="mt-4 flex items-center justify-center gap-4 text-xs">
              <div className="flex items-center gap-1">
                <div className="w-3 h-3 rounded bg-emerald-500" />
                <span>80%+</span>
              </div>
              <div className="flex items-center gap-1">
                <div className="w-3 h-3 rounded bg-lime-500" />
                <span>60-79%</span>
              </div>
              <div className="flex items-center gap-1">
                <div className="w-3 h-3 rounded bg-yellow-500" />
                <span>40-59%</span>
              </div>
              <div className="flex items-center gap-1">
                <div className="w-3 h-3 rounded bg-orange-500" />
                <span>20-39%</span>
              </div>
              <div className="flex items-center gap-1">
                <div className="w-3 h-3 rounded bg-red-500" />
                <span>&lt;20%</span>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Gap Analysis */}
      <Card>
        <CardHeader>
          <CardTitle>Gap Analysis & Recommendations</CardTitle>
        </CardHeader>
        <CardContent>
          <GapAnalysis scores={scores} />
        </CardContent>
      </Card>

      {/* History */}
      {allAssessments.length > 1 && (
        <Card>
          <CardHeader>
            <CardTitle>Assessment History</CardTitle>
          </CardHeader>
          <CardContent>
            <AssessmentHistory assessments={allAssessments} />
          </CardContent>
        </Card>
      )}
    </div>
  );
};
